// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxY2K2EqiWFaxuC7b3S5BLTYyDuRG8IwI',
    appId: '1:857485191884:web:338bb08cddadf96f137069',
    messagingSenderId: '857485191884',
    projectId: 'auth-92321',
    authDomain: 'auth-92321.firebaseapp.com',
    storageBucket: 'auth-92321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRoVwlbW9pCxDcdca9Fp2waoATno9bf4',
    appId: '1:857485191884:android:df8fcd36e7ece012137069',
    messagingSenderId: '857485191884',
    projectId: 'auth-92321',
    storageBucket: 'auth-92321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-E6zJqlQiSDLqgZmDY3pmcp1qXrag3k4',
    appId: '1:857485191884:ios:35da97d8a3d1cffa137069',
    messagingSenderId: '857485191884',
    projectId: 'auth-92321',
    storageBucket: 'auth-92321.appspot.com',
    iosClientId: '857485191884-0hub0oukofhlpsi8ik0fat1n0nbu3dr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.inoutcheck',
  );
}
